from __future__ import annotations

from dataclasses import dataclass

import tomllib

from .. import infra


@dataclass(frozen=True)
class BakedImage:
    provider: str
    region: str
    image_id: str
    baked_at: str
    base_image: str
    docker_version: str = ""


def image_key(provider: str, region: str) -> str:
    return f"{provider}:{region}"


def read_runtime_images() -> dict[str, BakedImage]:
    # Deferred self-import: RUNTIME_IMAGES_TOML is patched by tests as a
    # flat cli.image_bake attribute -- looking it up through the package at
    # call time is what makes that patch take effect here.
    from .. import image_bake

    if not image_bake.RUNTIME_IMAGES_TOML.exists():
        return {}
    try:
        data = tomllib.loads(image_bake.RUNTIME_IMAGES_TOML.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    images = data.get("images")
    if not isinstance(images, dict):
        return {}
    result: dict[str, BakedImage] = {}
    for key, row in images.items():
        if not isinstance(row, dict):
            continue
        provider, _, region = str(key).partition(":")
        result[str(key)] = BakedImage(
            provider=provider,
            region=region,
            image_id=str(row.get("image_id", "")),
            baked_at=str(row.get("baked_at", "")),
            base_image=str(row.get("base_image", "")),
            docker_version=str(row.get("docker_version", "")),
        )
    return result


def write_runtime_image(provider: str, region: str, image_id: str, base_image: str, docker_version: str = "") -> None:
    from .. import image_bake

    images = read_runtime_images()
    key = image_key(provider, region)
    images[key] = BakedImage(
        provider=provider,
        region=region,
        image_id=image_id,
        baked_at=infra.timestamp(),
        base_image=base_image,
        docker_version=docker_version,
    )
    image_bake.RUNTIME_IMAGES_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by vidctl utils image-bake", ""]
    for row_key, image in sorted(images.items()):
        lines.append(f"[images.{infra.toml_value(row_key)}]")
        lines.append(f"image_id = {infra.toml_value(image.image_id)}")
        lines.append(f"baked_at = {infra.toml_value(image.baked_at)}")
        lines.append(f"base_image = {infra.toml_value(image.base_image)}")
        lines.append(f"docker_version = {infra.toml_value(image.docker_version)}")
        lines.append("")
    image_bake.RUNTIME_IMAGES_TOML.write_text("\n".join(lines), encoding="utf-8")


def lookup_image(provider: str, region: str) -> str | None:
    """Find a baked image for (provider, region), with two provider-specific
    special cases: gcp images are project-global (not region-scoped), and
    akamai images auto-replicate across regions -- see plan doc for both.
    oci images are region- AND compartment-scoped (unlike akamai), so they
    deliberately do NOT get the any-region fallback -- exact match only."""
    images = read_runtime_images()
    if provider == "gcp":
        entry = images.get(image_key("gcp", "global"))
        return entry.image_id if entry else None
    exact = images.get(image_key(provider, region))
    if exact:
        return exact.image_id
    if provider == "akamai":
        for entry in images.values():
            if entry.provider == "akamai":
                return entry.image_id
    return None


def list_images() -> int:
    images = read_runtime_images()
    if not images:
        print("No golden images baked yet.")
        return 0
    for key, image in sorted(images.items()):
        print(f"{key}: {image.image_id} (baked {image.baked_at}, base {image.base_image})")
    return 0
