from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import tomllib

from . import infra
from .context import RUNTIME_IMAGES_TOML, command_env

# Providers with a real create_vm() adapter AND a documented (even if
# unverified for upcloud/akamai) native stop+create-image CLI path. Distinct
# from infra.PROVIDERS, which also includes tencent (no VM support at all)
# and cloudflare (no compute product) -- neither can ever be baked.
SUPPORTED_PROVIDERS = ("aws", "gcp", "azure", "alibaba", "digitalocean", "upcloud", "akamai")

# Best-effort fallback region to auto-bake into when a caller (e.g.
# cli/scenario.py's apply()) needs to ensure an image exists but the target
# instance doesn't have a resolved region yet (nothing persisted from a
# prior deploy, and the scenario file didn't set one explicitly). Mirrors
# IaC/pulumi/app/common/regions.py's _DEFAULTS -- duplicated deliberately
# rather than imported, since that module lives under the separate Pulumi
# program's Python path; NOT the source of truth for an actual VM's region
# (provider_region() inside the Pulumi program still decides that), only for
# picking where to bake by default. gcp uses its zone default (matches
# provider_zone(), not _DEFAULTS["gcp"]="US" which is a different concern).
DEFAULT_BAKE_REGIONS = {
    "aws": "us-east-1",
    "gcp": "us-central1-a",
    "azure": "eastus",
    "alibaba": "cn-hangzhou",
    "digitalocean": "nyc3",
    "upcloud": "fi-hel1",
    "akamai": "us-east",
}

BAKE_SERVICE = "__bake__"

BOOTSTRAP_SCRIPT = """
set -eu
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io
systemctl enable --now docker
docker --version || true

# Golden-image cleanup -- without this every VM cloned from the resulting
# image would share this bake VM's machine-id, SSH host keys, and cached
# cloud-init first-boot state, which is a real correctness/security problem
# (identical SSH host keys across independently-addressed hosts, stale
# per-instance metadata replayed instead of re-fetched, etc), not cosmetic.
apt-get clean
rm -rf /var/lib/apt/lists/*
if command -v cloud-init >/dev/null 2>&1; then
    cloud-init clean --logs || true
else
    rm -rf /var/lib/cloud/instances/* /var/lib/cloud/data/* || true
fi
rm -f /etc/machine-id
touch /etc/machine-id
rm -f /etc/ssh/ssh_host_*
history -c || true
rm -f /root/.bash_history
"""

# Azure requires Linux deprovisioning before `az vm generalize` -- run this
# right before shutdown, azure-only.
AZURE_DEPROVISION_SCRIPT = "waagent -deprovision+user -force"


@dataclass(frozen=True)
class BakedImage:
    provider: str
    region: str
    image_id: str
    baked_at: str
    base_image: str
    docker_version: str = ""


def image_key(provider: str, region: str) -> str:
    return f"{provider}:{region}"


def read_runtime_images() -> dict[str, BakedImage]:
    if not RUNTIME_IMAGES_TOML.exists():
        return {}
    try:
        data = tomllib.loads(RUNTIME_IMAGES_TOML.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    images = data.get("images")
    if not isinstance(images, dict):
        return {}
    result: dict[str, BakedImage] = {}
    for key, row in images.items():
        if not isinstance(row, dict):
            continue
        provider, _, region = str(key).partition(":")
        result[str(key)] = BakedImage(
            provider=provider,
            region=region,
            image_id=str(row.get("image_id", "")),
            baked_at=str(row.get("baked_at", "")),
            base_image=str(row.get("base_image", "")),
            docker_version=str(row.get("docker_version", "")),
        )
    return result


def write_runtime_image(provider: str, region: str, image_id: str, base_image: str, docker_version: str = "") -> None:
    images = read_runtime_images()
    key = image_key(provider, region)
    images[key] = BakedImage(
        provider=provider,
        region=region,
        image_id=image_id,
        baked_at=infra.timestamp(),
        base_image=base_image,
        docker_version=docker_version,
    )
    RUNTIME_IMAGES_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by vidctl utils image-bake", ""]
    for row_key, image in sorted(images.items()):
        lines.append(f"[images.{infra.toml_value(row_key)}]")
        lines.append(f"image_id = {infra.toml_value(image.image_id)}")
        lines.append(f"baked_at = {infra.toml_value(image.baked_at)}")
        lines.append(f"base_image = {infra.toml_value(image.base_image)}")
        lines.append(f"docker_version = {infra.toml_value(image.docker_version)}")
        lines.append("")
    RUNTIME_IMAGES_TOML.write_text("\n".join(lines), encoding="utf-8")


def lookup_image(provider: str, region: str) -> str | None:
    """Find a baked image for (provider, region), with two provider-specific
    special cases: gcp images are project-global (not region-scoped), and
    akamai images auto-replicate across regions -- see plan doc for both."""
    images = read_runtime_images()
    if provider == "gcp":
        entry = images.get(image_key("gcp", "global"))
        return entry.image_id if entry else None
    exact = images.get(image_key(provider, region))
    if exact:
        return exact.image_id
    if provider == "akamai":
        for entry in images.values():
            if entry.provider == "akamai":
                return entry.image_id
    return None


def list_images() -> int:
    images = read_runtime_images()
    if not images:
        print("No golden images baked yet.")
        return 0
    for key, image in sorted(images.items()):
        print(f"{key}: {image.image_id} (baked {image.baked_at}, base {image.base_image})")
    return 0


def new_bake_worker(env_name: str, provider: str, region: str) -> dict[str, Any]:
    host = f"bake-{provider}-{region}-{int(time.time())}".replace(".", "-").replace(":", "-")
    return {
        "host": host,
        "service": BAKE_SERVICE,
        "provider": provider,
        "env": env_name,
        "backend": "vm",
        "worker_index": 1,
        "desired_state": "running",
        "region": region,
    }


def provider_cli_env() -> dict[str, str]:
    """command_env(), plus env var aliases the provider CLI tools
    (doctl/aws/gcloud/az/aliyun/upctl/linode-cli) expect but that don't
    match secrets/cloud/*.env's Pulumi-provider-oriented names. Applied
    unconditionally -- an alias irrelevant to whichever CLI is actually
    being invoked in a given call is simply unused, not harmful.

    aws cli reads AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY directly (already
    loaded as-is). aliyun cli reads ALIBABA_CLOUD_ACCESS_KEY_ID/_SECRET
    directly (already loaded as-is via context.py's ALICLOUD_* mapping).
    gcloud/az need an actual authenticated `gcloud auth`/`az login` session,
    not just env vars -- not fixable with a simple alias, flagged as a real
    gap (see the bake plan's risk list) until that bootstrap step exists.
    """
    env = command_env()
    aliases = {
        "DIGITALOCEAN_ACCESS_TOKEN": "DIGITALOCEAN_TOKEN",  # doctl
        "LINODE_CLI_TOKEN": "LINODE_TOKEN",  # linode-cli
    }
    for new_key, old_key in aliases.items():
        if env.get(old_key) and not env.get(new_key):
            env[new_key] = env[old_key]
    return env


def run_capture(args: list[str], *, timeout: int | None = None) -> tuple[int, str, str]:
    try:
        result = subprocess.run(
            args, capture_output=True, text=True, timeout=timeout, env=provider_cli_env(), check=False
        )
        return result.returncode, result.stdout, result.stderr
    except (subprocess.TimeoutExpired, OSError) as exc:
        return 1, "", str(exc)


def ssh_run(address: str, key_path: Path, script: str, *, timeout: int = 300) -> tuple[int, str, str]:
    try:
        result = subprocess.run(
            [
                "ssh",
                "-o", "StrictHostKeyChecking=no",
                "-o", "ConnectTimeout=15",
                "-i", str(key_path),
                f"root@{address}",
                "bash -s",
            ],
            input=script,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=command_env(),
            check=False,
        )
        return result.returncode, result.stdout, result.stderr
    except (subprocess.TimeoutExpired, OSError) as exc:
        return 1, "", str(exc)


def wait_for_ssh(address: str, key_path: Path, *, attempts: int = 24, delay_seconds: float = 5.0) -> bool:
    """Poll until sshd on a freshly-created VM actually accepts connections.

    Cloud APIs commonly report a VM as active with an IP assigned well
    before its sshd is actually reachable -- attempting the real bootstrap
    script immediately after that races a "Connection refused" window of a
    few seconds up to roughly a minute, depending on provider/image boot
    time. Default budget: ~24 * 5s = 120s.
    """
    for _ in range(attempts):
        code, _, _ = run_capture(
            [
                "ssh",
                "-o", "StrictHostKeyChecking=no",
                "-o", "ConnectTimeout=8",
                "-o", "BatchMode=yes",
                "-i", str(key_path),
                f"root@{address}",
                "true",
            ],
            timeout=12,
        )
        if code == 0:
            return True
        time.sleep(delay_seconds)
    return False


def provider_error(provider: str) -> str | None:
    if provider not in SUPPORTED_PROVIDERS:
        return (
            f"'{provider}' does not support golden-image baking "
            f"(supported: {', '.join(SUPPORTED_PROVIDERS)})."
        )
    return None


def _stop_and_create_image(provider: str, address: str, region: str, resource_id: str, image_name: str) -> tuple[bool, str, str]:
    """Stop the bake VM and create a provider-native image/snapshot from it.

    Returns (success, image_id, error_message). Commands below are the
    documented/best-confidence CLI invocations per provider (see plan doc);
    upcloud and akamai flags are explicitly best-effort/unverified -- confirm
    against `upctl --help` / `linode-cli images create --help` before relying
    on them for a real bake.
    """
    if provider == "aws":
        code, _, err = run_capture(["aws", "ec2", "stop-instances", "--instance-ids", resource_id, "--region", region])
        if code != 0:
            return False, "", f"aws ec2 stop-instances failed: {err}"
        run_capture(["aws", "ec2", "wait", "instance-stopped", "--instance-ids", resource_id, "--region", region], timeout=600)
        code, out, err = run_capture(
            ["aws", "ec2", "create-image", "--instance-id", resource_id, "--name", image_name, "--region", region, "--output", "text", "--query", "ImageId"]
        )
        if code != 0 or not out.strip():
            return False, "", f"aws ec2 create-image failed: {err}"
        return True, out.strip(), ""

    if provider == "gcp":
        code, _, err = run_capture(["gcloud", "compute", "instances", "stop", resource_id, "--zone", region])
        if code != 0:
            return False, "", f"gcloud compute instances stop failed: {err}"
        code, out, err = run_capture(
            ["gcloud", "compute", "images", "create", image_name, "--source-disk", resource_id, "--source-disk-zone", region, "--format", "value(name)"]
        )
        if code != 0 or not out.strip():
            return False, "", f"gcloud compute images create failed: {err}"
        return True, out.strip(), ""

    if provider == "azure":
        # resource_id here is the deterministic VM name azure.py now sets
        # (f"{name}-vm"); all azure VMs share the "xaisen-rg" resource
        # group (azure.py's shared_network(), also now given a deterministic
        # name) rather than an autogenerated one.
        resource_group = "xaisen-rg"
        code, _, err = run_capture(["az", "vm", "deallocate", "--resource-group", resource_group, "--name", resource_id])
        if code != 0:
            return False, "", f"az vm deallocate failed: {err}"
        code, _, err = run_capture(["az", "vm", "generalize", "--resource-group", resource_group, "--name", resource_id])
        if code != 0:
            return False, "", f"az vm generalize failed: {err}"
        code, out, err = run_capture(
            ["az", "image", "create", "--resource-group", resource_group, "--name", image_name, "--source", resource_id, "--query", "id", "-o", "tsv"]
        )
        if code != 0 or not out.strip():
            return False, "", f"az image create failed: {err}"
        return True, out.strip(), ""

    if provider == "alibaba":
        code, _, err = run_capture(["aliyun", "ecs", "StopInstance", "--InstanceId", resource_id, "--RegionId", region])
        if code != 0:
            return False, "", f"aliyun ecs StopInstance failed: {err}"
        code, out, err = run_capture(
            ["aliyun", "ecs", "CreateImage", "--RegionId", region, "--InstanceId", resource_id, "--ImageName", image_name]
        )
        if code != 0 or not out.strip():
            return False, "", f"aliyun ecs CreateImage failed: {err}"
        try:
            image_id = json.loads(out).get("ImageId", "")
        except ValueError:
            image_id = ""
        if not image_id:
            return False, "", f"Could not parse ImageId from aliyun output: {out}"
        return True, image_id, ""

    if provider == "digitalocean":
        code, _, err = run_capture(["doctl", "compute", "droplet-action", "shutdown", resource_id, "--wait"])
        if code != 0:
            return False, "", f"doctl droplet-action shutdown failed: {err}"
        code, out, err = run_capture(
            ["doctl", "compute", "droplet-action", "snapshot", resource_id, "--snapshot-name", image_name, "--wait", "--format", "Resource", "--no-header"]
        )
        if code != 0:
            return False, "", f"doctl droplet-action snapshot failed: {err}"
        # doctl's snapshot action doesn't directly return the new image ID --
        # look it up by name.
        code, out, err = run_capture(["doctl", "compute", "image", "list", "--format", "ID,Name", "--no-header"])
        if code != 0:
            return False, "", f"doctl compute image list failed: {err}"
        for line in out.splitlines():
            parts = line.split(None, 1)
            if len(parts) == 2 and parts[1].strip() == image_name:
                return True, parts[0].strip(), ""
        return False, "", f"Could not find snapshot '{image_name}' in doctl compute image list output."

    if provider == "upcloud":
        # UNVERIFIED -- confirm exact upctl subcommands/flags before relying
        # on this for a real bake (pulumi_upcloud/upctl were not available to
        # confirm locally).
        code, _, err = run_capture(["upctl", "server", "stop", resource_id, "--wait"])
        if code != 0:
            return False, "", f"upctl server stop failed (unverified command): {err}"
        code, out, err = run_capture(["upctl", "storage", "clone", resource_id, "--title", image_name, "--zone", region])
        if code != 0 or not out.strip():
            return False, "", f"upctl storage clone failed (unverified command): {err}"
        return True, out.strip(), ""

    if provider == "akamai":
        # UNVERIFIED -- confirm exact linode-cli flags before relying on this
        # for a real bake (pulumi_linode/linode-cli were not available to
        # confirm locally).
        code, _, err = run_capture(["linode-cli", "linodes", "shutdown", resource_id])
        if code != 0:
            return False, "", f"linode-cli linodes shutdown failed (unverified command): {err}"
        code, out, err = run_capture(
            ["linode-cli", "images", "create", "--disk_id", resource_id, "--label", image_name, "--text", "--no-headers", "--format", "id"]
        )
        if code != 0 or not out.strip():
            return False, "", f"linode-cli images create failed (unverified command): {err}"
        return True, out.strip().splitlines()[0], ""

    return False, "", f"No image-creation path implemented for provider '{provider}'."


def resolve_bake_region(provider: str, region: str | None) -> str:
    """Pick the region to check/bake for when the caller doesn't already
    have a resolved one (e.g. a first-ever deploy with nothing persisted to
    topology.toml yet). Explicit region wins; otherwise DEFAULT_BAKE_REGIONS."""
    return region or DEFAULT_BAKE_REGIONS.get(provider, "")


def ensure_image(provider: str, region: str | None) -> tuple[bool, str]:
    """Bake an image for (provider, region) if one doesn't already exist.

    Returns (ok, error_message). A no-op (ok=True, "") if an image is
    already baked, or if the provider doesn't support baking at all (falls
    through to that provider's stock-image behavior, unchanged).
    """
    if provider not in SUPPORTED_PROVIDERS:
        return True, ""
    resolved_region = resolve_bake_region(provider, region)
    if not resolved_region:
        return False, f"Could not determine a region to bake {provider} into."
    if lookup_image(provider, resolved_region):
        return True, ""
    print(f"No golden image baked yet for {provider}:{resolved_region} -- baking one now...")
    code = bake(provider, resolved_region, True)
    if code != 0:
        return False, f"Baking {provider}:{resolved_region} failed (exit {code})."
    return True, ""


def bake(provider: str, region: str, yes: bool) -> int:
    error = provider_error(provider)
    if error:
        print(error, file=sys.stderr)
        return 2
    if not yes:
        print(
            "Refusing to bake a golden image without --yes (this provisions a "
            "real, temporary, billable cloud VM and creates an image/snapshot).",
            file=sys.stderr,
        )
        return 2

    missing = infra.missing_vm_provider_keys(provider)
    if missing:
        print(infra.vm_provider_error(provider, missing), file=sys.stderr)
        return 1

    # ensure_topology (not read_topology) since topology.toml may not exist
    # yet on a first-ever bake -- mirrors cli/scenario.py's same fix.
    env_name = infra.active_stack()
    topology = infra.ensure_topology(env_name)
    bake_worker = new_bake_worker(env_name, provider, region)
    infra.set_vm_defaults(bake_worker, topology)
    # A bake VM must always use the stock image (it's what's being turned
    # INTO a golden image) -- never a previously-baked one.
    bake_worker.pop("image", None)
    topology.setdefault("workers", []).append(bake_worker)
    infra.write_topology(topology)

    host = bake_worker["host"]

    def _abort(message: str, remove_row: bool) -> int:
        print(message, file=sys.stderr)
        if remove_row:
            current = infra.read_topology()
            current["workers"] = [i for i in current.get("workers", []) if i.get("host") != host]
            infra.write_topology(current)
        return 1

    code = infra.pulumi_up(env_name)
    if code != 0:
        return _abort(f"Bake failed provisioning the temporary VM (exit {code}).", remove_row=True)

    code = infra.inventory()
    if code != 0:
        return _abort(
            f"Bake VM '{host}' provisioned but inventory generation failed (exit {code}). "
            "Left in place for inspection -- run 'vidctl infra inventory' manually or clean up by "
            "removing its topology row and re-running pulumi up.",
            remove_row=False,
        )

    infra.persist_vm_resolution(topology, env_name, host, BAKE_SERVICE, provider)
    resolved = infra.find_worker(topology, env_name, host, BAKE_SERVICE, provider) or bake_worker
    resolved_region = str(resolved.get("region") or resolved.get("zone") or region)

    address = infra.host_address(host)
    if not address:
        return _abort(
            f"Bake VM '{host}' provisioned but has no resolved address. Left in place for inspection.",
            remove_row=False,
        )

    key_path = infra.SSH_KEY_ROOT / host / "id_ed25519"
    print(f"Waiting for SSH on {address} ...")
    if not wait_for_ssh(address, key_path):
        return _abort(
            f"Bake VM '{host}' ({address}) never became SSH-reachable. Left in place for inspection.",
            remove_row=False,
        )

    print(f"Bootstrapping Docker on {address} ...")
    ssh_code, ssh_out, ssh_err = ssh_run(address, key_path, BOOTSTRAP_SCRIPT)
    if ssh_code != 0:
        return _abort(
            f"Bake VM '{host}' ({address}) bootstrap script failed (exit {ssh_code}): {ssh_err or ssh_out}. "
            "Left in place for inspection.",
            remove_row=False,
        )
    docker_version = ""
    for line in ssh_out.splitlines():
        if line.startswith("Docker version"):
            docker_version = line.split("Docker version", 1)[-1].split(",")[0].strip()

    if provider == "azure":
        ssh_code, _, ssh_err = ssh_run(address, key_path, AZURE_DEPROVISION_SCRIPT)
        if ssh_code != 0:
            return _abort(
                f"Bake VM '{host}' ({address}) azure deprovision step failed (exit {ssh_code}): {ssh_err}. "
                "Left in place for inspection.",
                remove_row=False,
            )

    resource_id = str(resolved.get("resource_id") or host)
    image_name = f"xaisen-golden-{provider}-{resolved_region}-{int(time.time())}"
    print(f"Stopping VM and creating image '{image_name}' ...")
    success, image_id, error_message = _stop_and_create_image(
        provider, address, resolved_region, resource_id, image_name
    )
    if not success:
        return _abort(
            f"Bake VM '{host}' ({address}) image creation failed: {error_message}. Left in place for inspection.",
            remove_row=False,
        )

    write_runtime_image(provider, resolved_region, image_id, base_image="ubuntu-22.04", docker_version=docker_version)
    print(f"Baked {provider}:{resolved_region} -> {image_id}")

    current = infra.read_topology()
    current["workers"] = [i for i in current.get("workers", []) if i.get("host") != host]
    infra.write_topology(current)
    teardown_code = infra.pulumi_up(env_name)
    shutil.rmtree(infra.SSH_KEY_ROOT / host, ignore_errors=True)
    if teardown_code != 0:
        print(
            f"Warning: image baked successfully but tearing down bake VM '{host}' failed "
            f"(exit {teardown_code}); it may still be running and billing.",
            file=sys.stderr,
        )
        return teardown_code
    return 0
