from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import tomllib

from .context import (
    ANSIBLE_DIR,
    DOCKER_SERVICES,
    GENERATED_INVENTORY,
    PULUMI_DIR,
    RUNTIME_HISTORY_TOML,
    RUNTIME_TOPOLOGY_TOML,
    command_env,
    contract_env_path,
    read_env_file,
    run,
    venv_bin,
)

NETWORKS = ("devnet", "testnet", "mainnet")
PROVIDERS = ("aws", "gcp", "azure", "alibaba", "digitalocean", "tencent")
REQUIRED_CONTRACT_KEYS = ("CONTRACT_PACKAGE_ID", "CONTRACT_REGISTRY_OBJECT_ID")


def pulumi_stack(default: str | None = None) -> str:
    return default or command_env().get("PULUMI_STACK", "dev")


def init(env_name: str | None = None) -> int:
    stack = validate_network(env_name or command_env().get("PULUMI_STACK", "dev"))
    topology = ensure_topology(stack)
    code = select_or_create_stack(stack)
    record_history(
        command="infra init",
        env=stack,
        result="success" if code == 0 else "failure",
        exit_code=code,
    )
    if code == 0:
        print(f"Initialized topology {RUNTIME_TOPOLOGY_TOML} for {topology['active_env']}")
    return code


def preview() -> int:
    stack = active_stack()
    code = run(["pulumi", "preview", "--stack", stack], cwd=PULUMI_DIR)
    record_history("infra preview", env=stack, result_for_code=code)
    return code


def apply(yes: bool) -> int:
    stack = active_stack()
    if not yes:
        code = 2
        message = "Refusing to apply infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history("infra apply", env=stack, result_for_code=code, error=message)
        return code
    code = pulumi_up(stack)
    if code == 0:
        code = inventory()
    record_history("infra apply", env=stack, result_for_code=code)
    return code


def inventory() -> int:
    stack = active_stack()
    try:
        raw = subprocess.check_output(
            ["pulumi", "stack", "output", "ansibleInventory", "--json", "--stack", stack],
            cwd=PULUMI_DIR,
            env=command_env(),
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        record_history("infra inventory", env=stack, result_for_code=exc.returncode, error=str(exc))
        return exc.returncode or 1

    try:
        import yaml
    except ImportError:
        message = "PyYAML is missing. Run: ./vidctl bootstrap"
        print(message, file=sys.stderr)
        record_history("infra inventory", env=stack, result_for_code=1, error=message)
        return 1

    GENERATED_INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_INVENTORY.write_text(
        "# Generated by ./vidctl infra inventory\n" + yaml.safe_dump(json.loads(raw), sort_keys=False),
        encoding="utf-8",
    )
    record_history("infra inventory", env=stack, result="success", exit_code=0)
    return 0


def ansible_inventory() -> int:
    executable = venv_bin("ansible-inventory")
    if not executable.exists():
        print("Ansible is missing. Run: ./vidctl bootstrap", file=sys.stderr)
        return 1
    return run([executable, "--list"], cwd=ANSIBLE_DIR)


def ping() -> int:
    code = ansible_playbook("ping.yml")
    record_history("infra ping", env=active_stack(), result_for_code=code)
    return code


def configure() -> int:
    code = ansible_playbook("site.yml")
    record_history("infra configure", env=active_stack(), result_for_code=code)
    return code


def deploy(yes: bool) -> int:
    if not yes:
        message = "Refusing to deploy infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history("infra deploy", env=active_stack(), result_for_code=2, error=message)
        return 2
    code = apply(yes=True)
    if code == 0:
        code = configure()
    record_history("infra deploy", env=active_stack(), result_for_code=code)
    return code


def control(action: str, name: str, service: str, provider: str, yes: bool = False) -> int:
    if service not in DOCKER_SERVICES:
        print(f"Unknown service: {service}", file=sys.stderr)
        return 2
    if provider not in PROVIDERS:
        print(f"Unknown provider: {provider}", file=sys.stderr)
        return 2

    topology = read_topology()
    env_name = validate_network(str(topology.get("active_env", "devnet")))
    contract_path = contract_env_path(env_name)
    if action in {"start", "restart"}:
        missing_keys = missing_contract_keys(contract_path)
        if missing_keys:
            message = (
                f"{contract_path} is missing required contract keys: "
                + ", ".join(missing_keys)
                + f". Run ./vidctl contract publish --env {env_name} --yes first."
            )
            print(message, file=sys.stderr)
            record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
            return 1

    if action == "kill" and not yes:
        message = "Refusing to delete infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=2, error=message)
        return 2

    instance = find_instance(topology, env_name, name, service, provider)
    if instance is None:
        message = f"No topology instance named {name!r} for service {service!r} on provider {provider!r} in {env_name}."
        print(message, file=sys.stderr)
        record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
        return 1

    previous = str(instance.get("desired_state", instance.get("last_status", "unknown")))
    next_state = desired_state_for(action)
    instance["desired_state"] = next_state
    instance["last_operation"] = action
    instance["last_updated"] = timestamp()
    instance["contract_env"] = relative_contract_env(env_name)
    write_topology(topology)

    code = pulumi_up(env_name)
    if code == 0:
        instance["last_status"] = "terminated" if action == "kill" else next_state
        instance["last_error"] = ""
        write_topology(topology)
        if action in {"start", "restart"}:
            inventory()
            configure()
    else:
        instance["last_error"] = f"pulumi up failed with exit code {code}"
        write_topology(topology)

    record_history(
        action,
        env=env_name,
        name=name,
        service=service,
        provider=str(instance.get("provider", "")),
        resource_id=str(instance.get("resource_id", "")),
        previous_status=previous,
        next_status=str(instance.get("desired_state", "")),
        result_for_code=code,
        error=str(instance.get("last_error", "")),
    )
    return code


def ansible_playbook(playbook: str) -> int:
    executable = venv_bin("ansible-playbook")
    if not executable.exists():
        print("Ansible is missing. Run: ./vidctl bootstrap", file=sys.stderr)
        return 1
    return run([executable, f"playbooks/{playbook}"], cwd=ANSIBLE_DIR)


def select_or_create_stack(stack: str) -> int:
    env = command_env()
    env["PULUMI_STACK"] = stack
    selected = subprocess.run(
        ["pulumi", "stack", "select", stack],
        cwd=PULUMI_DIR,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if selected.returncode == 0:
        print(f"Selected Pulumi stack {stack}")
        return 0
    return run(["pulumi", "stack", "init", stack], cwd=PULUMI_DIR, env=env)


def pulumi_up(stack: str) -> int:
    env = command_env()
    env["PULUMI_STACK"] = stack
    return run(["pulumi", "up", "--yes", "--stack", stack], cwd=PULUMI_DIR, env=env)


def active_stack() -> str:
    if RUNTIME_TOPOLOGY_TOML.exists():
        return validate_network(str(read_topology().get("active_env", "devnet")))
    stack = command_env().get("PULUMI_STACK", "devnet")
    return stack if stack in NETWORKS else "devnet"


def ensure_topology(env_name: str) -> dict[str, Any]:
    topology = read_topology() if RUNTIME_TOPOLOGY_TOML.exists() else {}
    topology["active_env"] = env_name
    topology["contract_env"] = relative_contract_env(env_name)
    topology.setdefault("providers", {provider: {"enabled": False} for provider in PROVIDERS})
    for provider in PROVIDERS:
        topology["providers"].setdefault(provider, {"enabled": False})
    topology.setdefault("instances", [])
    write_topology(topology)
    return topology


def read_topology() -> dict[str, Any]:
    if not RUNTIME_TOPOLOGY_TOML.exists():
        return ensure_topology("devnet")
    data = tomllib.loads(RUNTIME_TOPOLOGY_TOML.read_text(encoding="utf-8"))
    data.setdefault("instances", [])
    data.setdefault("providers", {})
    return data


def write_topology(topology: dict[str, Any]) -> None:
    RUNTIME_TOPOLOGY_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# generated by vidctl",
        f'active_env = "{topology.get("active_env", "devnet")}"',
        f'contract_env = "{topology.get("contract_env", relative_contract_env(str(topology.get("active_env", "devnet"))))}"',
        "",
    ]
    providers = topology.get("providers", {})
    for provider in PROVIDERS:
        values = providers.get(provider, {"enabled": False}) if isinstance(providers, dict) else {"enabled": False}
        lines.append(f"[providers.{provider}]")
        for key, value in sorted(values.items()):
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    for instance in topology.get("instances", []):
        lines.append("[[instances]]")
        for key, value in instance.items():
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    RUNTIME_TOPOLOGY_TOML.write_text("\n".join(lines), encoding="utf-8")


def find_instance(
    topology: dict[str, Any],
    env_name: str,
    name: str,
    service: str,
    provider: str,
) -> dict[str, Any] | None:
    for instance in topology.get("instances", []):
        if (
            instance.get("name") == name
            and instance.get("service") == service
            and instance.get("provider") == provider
            and instance.get("env", env_name) == env_name
        ):
            return instance
    return None


def missing_contract_keys(path: Path) -> list[str]:
    values = read_env_file(path)
    return [key for key in REQUIRED_CONTRACT_KEYS if not values.get(key)]


def validate_network(env_name: str) -> str:
    if env_name not in NETWORKS:
        raise ValueError(f"Unsupported environment {env_name!r}; expected one of {', '.join(NETWORKS)}.")
    return env_name


def desired_state_for(action: str) -> str:
    return {
        "start": "running",
        "pause": "stopped",
        "restart": "running",
        "kill": "deleted",
    }[action]


def relative_contract_env(env_name: str) -> str:
    return f"runtime/contract/{env_name}.env"


def record_history(
    command: str,
    *,
    env: str,
    result: str | None = None,
    result_for_code: int | None = None,
    exit_code: int | None = None,
    name: str = "",
    service: str = "",
    provider: str = "",
    resource_id: str = "",
    previous_status: str = "",
    next_status: str = "",
    error: str = "",
) -> None:
    if result_for_code is not None:
        exit_code = result_for_code
        result = "success" if result_for_code == 0 else "failure"
    if result is None:
        result = "success"
    if exit_code is None:
        exit_code = 0 if result == "success" else 1

    event = {
        "timestamp": timestamp(),
        "command": command,
        "env": env,
        "name": name,
        "service": service,
        "provider": provider,
        "resource_id": resource_id,
        "previous_status": previous_status,
        "next_status": next_status,
        "result": result,
        "exit_code": exit_code,
        "error": error,
    }
    RUNTIME_HISTORY_TOML.parent.mkdir(parents=True, exist_ok=True)
    with RUNTIME_HISTORY_TOML.open("a", encoding="utf-8") as history:
        history.write("[[events]]\n")
        for key, value in event.items():
            history.write(f"{key} = {toml_value(value)}\n")
        history.write("\n")


def timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if value is None:
        return '""'
    return json.dumps(str(value))
