from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import tomllib

from .context import (
    ANSIBLE_DIR,
    DOCKER_SERVICES,
    GENERATED_INVENTORY,
    PULUMI_DIR,
    ROOT,
    RUNTIME_HISTORY_TOML,
    RUNTIME_TOPOLOGY_TOML,
    command_env,
    contract_env_path,
    read_env_file,
    run,
    venv_bin,
)

NETWORKS = ("devnet", "testnet", "mainnet")
PROVIDERS = ("aws", "gcp", "azure", "alibaba", "digitalocean", "tencent", "cloudflare")
OBJECT_STORAGE_SERVICE = "frontend"
SERVICE_BACKENDS = {service: "vm" for service in DOCKER_SERVICES}
SERVICE_BACKENDS[OBJECT_STORAGE_SERVICE] = "object_storage"
REQUIRED_CONTRACT_KEYS = ("CONTRACT_PACKAGE_ID", "CONTRACT_REGISTRY_OBJECT_ID")
SERVICE_PORTS = {"routes": 3001, "coordinator": 6379, "media": 7880}
VM_INSTANCE_SIZES = {
    "aws": "t3.micro",
    "gcp": "e2-micro",
    "azure": "Standard_B1s",
    "alibaba": "ecs.t6-c1m1.large",
    "digitalocean": "s-1vcpu-1gb",
    "tencent": "S5.SMALL1",
}
SSH_KEY_ROOT = ROOT / "runtime" / "ssh_key"


def pulumi_stack(default: str | None = None) -> str:
    return default or command_env().get("PULUMI_STACK", "dev")


def init(env_name: str | None = None) -> int:
    stack = validate_network(env_name or command_env().get("PULUMI_STACK", "dev"))
    topology = ensure_topology(stack)
    code = select_or_create_stack(stack)
    record_history(
        command="infra init",
        env=stack,
        result="success" if code == 0 else "failure",
        exit_code=code,
    )
    if code == 0:
        print(f"Initialized topology {RUNTIME_TOPOLOGY_TOML} for {topology['active_env']}")
    return code


def preview() -> int:
    stack = active_stack()
    code = run(["pulumi", "preview", "--stack", stack], cwd=PULUMI_DIR)
    record_history("infra preview", env=stack, result_for_code=code)
    return code


def apply(yes: bool) -> int:
    stack = active_stack()
    if not yes:
        code = 2
        message = "Refusing to apply infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history("infra apply", env=stack, result_for_code=code, error=message)
        return code

    code = prepare_running_frontend_artifacts(stack)
    if code == 0:
        code = pulumi_up(stack)
    if code == 0:
        code = inventory()
    record_history("infra apply", env=stack, result_for_code=code)
    return code


def inventory() -> int:
    stack = active_stack()
    try:
        raw = subprocess.check_output(
            ["pulumi", "stack", "output", "ansibleInventory", "--json", "--stack", stack],
            cwd=PULUMI_DIR,
            env=command_env(),
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        message = f"Unable to read Pulumi ansibleInventory output: {exc}"
        print(message, file=sys.stderr)
        record_history("infra inventory", env=stack, result_for_code=1, error=message)
        return 1

    try:
        import yaml
    except ImportError:
        message = "PyYAML is missing. Run: ./vidctl bootstrap"
        print(message, file=sys.stderr)
        record_history("infra inventory", env=stack, result_for_code=1, error=message)
        return 1

    GENERATED_INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_INVENTORY.write_text(
        "# Generated by ./vidctl infra inventory\n" + yaml.safe_dump(json.loads(raw), sort_keys=False),
        encoding="utf-8",
    )
    record_history("infra inventory", env=stack, result="success", exit_code=0)
    return 0


def ansible_inventory() -> int:
    executable = venv_bin("ansible-inventory")
    if not executable.exists():
        print("Ansible is missing. Run: ./vidctl bootstrap", file=sys.stderr)
        return 1
    return run([executable, "--list"], cwd=ANSIBLE_DIR)


def ping() -> int:
    code = ansible_playbook("ping.yml")
    record_history("infra ping", env=active_stack(), result_for_code=code)
    return code


def configure(host_limit: str | None = None, container_state: str = "started") -> int:
    extra_vars = docker_deploy_extra_vars()
    extra_vars["xaisen_container_state"] = container_state
    code = ansible_playbook("site.yml", extra_vars=extra_vars, host_limit=host_limit)
    record_history("infra configure", env=active_stack(), result_for_code=code)
    return code


def docker_deploy_extra_vars() -> dict[str, Any]:
    from . import registry

    try:
        state = registry.read_runtime_registry()
    except ValueError as exc:
        print(f"Skipping docker image deployment: {exc}", file=sys.stderr)
        return {}

    extra_vars: dict[str, Any] = {
        "xaisen_images": state.images,
        "xaisen_tags": state.deployed,
        "xaisen_registry_host": state.host,
    }
    try:
        config = registry.provider_config(state.provider, require_credentials=True)
    except ValueError as exc:
        print(f"Skipping registry login: {exc}", file=sys.stderr)
        return extra_vars
    extra_vars["xaisen_registry_username"] = config.username
    extra_vars["xaisen_registry_password"] = config.password
    return extra_vars


def deploy(yes: bool) -> int:
    if not yes:
        message = "Refusing to deploy infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history("infra deploy", env=active_stack(), result_for_code=2, error=message)
        return 2
    code = apply(yes=True)
    if code == 0:
        code = configure()
    record_history("infra deploy", env=active_stack(), result_for_code=code)
    return code


def control(action: str, name: str, service: str, provider: str, yes: bool = False) -> int:
    if service not in DOCKER_SERVICES:
        print(f"Unknown service: {service}", file=sys.stderr)
        return 2
    if provider not in PROVIDERS:
        print(f"Unknown provider: {provider}", file=sys.stderr)
        return 2

    topology = read_topology()
    env_name = validate_network(str(topology.get("active_env", "devnet")))
    contract_path = contract_env_path(env_name)
    backend = service_backend(service)

    if backend == "vm" and action in {"pause", "restart"} and provider != "alibaba":
        message = (
            f"{action} is not yet supported for {provider} VM services; "
            "powered lifecycle support currently requires --provider alibaba."
        )
        print(message, file=sys.stderr)
        record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
        return 1

    if action in {"start", "restart"}:
        missing_keys = missing_contract_keys(contract_path)
        if missing_keys:
            message = (
                f"{contract_path} is missing required contract keys: {', '.join(missing_keys)}. "
                f"Run ./vidctl contract publish --env {env_name} --yes first."
            )
            print(message, file=sys.stderr)
            record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
            return 1
        if backend == "object_storage":
            missing_provider_keys = missing_object_storage_provider_keys(provider)
            if missing_provider_keys:
                message = object_storage_provider_error(provider, missing_provider_keys)
                print(message, file=sys.stderr)
                record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
                return 1
        if backend == "vm":
            if provider == "cloudflare":
                message = "cloudflare has no compute/VM product; choose another --provider for vm-backed services."
                print(message, file=sys.stderr)
                record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
                return 1
            if provider == "tencent":
                message = (
                    "tencent VM provisioning is not yet supported (no working Pulumi Python SDK path was "
                    "found for Tencent compute/VPC resources); choose another --provider for now."
                )
                print(message, file=sys.stderr)
                record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
                return 1
            missing_provider_keys = missing_vm_provider_keys(provider)
            if missing_provider_keys:
                message = vm_provider_error(provider, missing_provider_keys)
                print(message, file=sys.stderr)
                record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=1, error=message)
                return 1

    if action == "kill" and not yes:
        message = "Refusing to delete infrastructure without --yes."
        print(message, file=sys.stderr)
        record_history(action, env=env_name, name=name, service=service, provider=provider, result_for_code=2, error=message)
        return 2

    instance = find_instance(topology, env_name, name, service, provider)
    if instance is None:
        instance = new_instance(env_name, name, service, provider)
        topology.setdefault("instances", []).append(instance)

    previous = str(instance.get("desired_state", instance.get("last_status", "unknown")))
    next_state = desired_state_for(action)
    instance["backend"] = backend
    instance["desired_state"] = next_state
    instance["last_operation"] = action
    instance["last_updated"] = timestamp()
    instance["contract_env"] = relative_contract_env(env_name)
    if backend == "object_storage":
        set_frontend_storage_defaults(instance, env_name)
    elif backend == "vm" and action in {"start", "restart"}:
        set_vm_defaults(instance)
    write_topology(topology)

    code = 0
    failed_stage = "pulumi"
    if backend == "object_storage" and action in {"start", "restart"}:
        failed_stage = "frontend build"
        code = build_frontend_static(env_name)
    if code == 0:
        failed_stage = "pulumi"
        if backend == "object_storage" and provider == "alibaba":
            code = pulumi_up(env_name, parallel=4)
        elif backend == "vm" and provider == "alibaba":
            code = pulumi_up(
                env_name,
                targets=alibaba_vm_target_urns(env_name, name, service, bool(instance.get("port"))),
            )
        else:
            code = pulumi_up(env_name)

    if code == 0:
        if action == "kill":
            topology["instances"] = [
                item
                for item in topology.get("instances", [])
                if not (
                    item.get("name") == name
                    and item.get("service") == service
                    and item.get("provider") == provider
                    and item.get("env", env_name) == env_name
                )
            ]
            if backend == "vm":
                shutil.rmtree(SSH_KEY_ROOT / name, ignore_errors=True)
        elif backend == "vm" and action in {"start", "restart"}:
            failed_stage = "inventory"
            code = inventory()
            if code == 0:
                failed_stage = "configure"
                container_state = "restarted" if action == "restart" else "started"
                code = configure(host_limit=name, container_state=container_state)

        if code == 0 and action != "kill":
            instance["last_status"] = next_state
            instance["last_error"] = ""
        write_topology(topology)

    if code != 0:
        if failed_stage in {"frontend build", "pulumi"}:
            instance["desired_state"] = previous
        instance["last_error"] = f"{failed_stage} failed with exit code {code}"
        write_topology(topology)

    record_history(
        action,
        env=env_name,
        name=name,
        service=service,
        provider=str(instance.get("provider", "")),
        resource_id=str(instance.get("resource_id", "")),
        previous_status=previous,
        next_status=str(instance.get("desired_state", "")),
        result_for_code=code,
        error=str(instance.get("last_error", "")),
    )
    return code


def ansible_playbook(
    playbook: str,
    extra_vars: dict[str, Any] | None = None,
    host_limit: str | None = None,
) -> int:
    executable = venv_bin("ansible-playbook")
    if not executable.exists():
        print("Ansible is missing. Run: ./vidctl bootstrap", file=sys.stderr)
        return 1
    args = [executable, f"playbooks/{playbook}"]
    if host_limit:
        args += ["--limit", host_limit]
    if extra_vars:
        args += ["--extra-vars", json.dumps(extra_vars)]
    return run(args, cwd=ANSIBLE_DIR)


def select_or_create_stack(stack: str) -> int:
    env = command_env()
    env["PULUMI_STACK"] = stack
    selected = subprocess.run(
        ["pulumi", "stack", "select", stack],
        cwd=PULUMI_DIR,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if selected.returncode == 0:
        print(f"Selected Pulumi stack {stack}")
        return 0
    return run(["pulumi", "stack", "init", stack], cwd=PULUMI_DIR, env=env)


def pulumi_up(stack: str, parallel: int | None = None, targets: list[str] | None = None) -> int:
    env = command_env()
    env["PULUMI_STACK"] = stack
    args = ["pulumi", "up", "--yes", "--stack", stack]
    for target in targets or []:
        args.extend(["--target", target])
    if parallel is not None:
        args.extend(["--parallel", str(parallel)])
    return run(args, cwd=PULUMI_DIR, env=env)


def alibaba_vm_target_urns(
    stack: str,
    name: str,
    service: str,
    has_service_port: bool,
) -> list[str]:
    prefix = f"urn:pulumi:{stack}::xaisen-iac::"
    resources = [
        ("pulumi:providers:alicloud", f"{name}-vm-provider"),
        ("alicloud:vpc/network:Network", f"{name}-vm-vpc"),
        ("alicloud:vpc/switch:Switch", f"{name}-vm-vswitch"),
        ("alicloud:ecs/keyPair:KeyPair", f"{name}-vm-key"),
        ("alicloud:ecs/securityGroup:SecurityGroup", f"{name}-vm-sg"),
        ("alicloud:ecs/securityGroupRule:SecurityGroupRule", f"{name}-vm-sg-ssh"),
        ("alicloud:ecs/instance:Instance", f"{name}-vm"),
    ]
    if service == "routes":
        resources.extend(
            [
                ("alicloud:ecs/securityGroupRule:SecurityGroupRule", f"{name}-vm-sg-http"),
                ("alicloud:ecs/securityGroupRule:SecurityGroupRule", f"{name}-vm-sg-https"),
            ]
        )
    elif has_service_port:
        resources.append(("alicloud:ecs/securityGroupRule:SecurityGroupRule", f"{name}-vm-sg-port"))
    return [f"{prefix}{resource_type}::{resource_name}" for resource_type, resource_name in resources]


def active_stack() -> str:
    if RUNTIME_TOPOLOGY_TOML.exists():
        return validate_network(str(read_topology().get("active_env", "devnet")))
    stack = command_env().get("PULUMI_STACK", "devnet")
    return stack if stack in NETWORKS else "devnet"


def ensure_topology(env_name: str) -> dict[str, Any]:
    topology = read_topology() if RUNTIME_TOPOLOGY_TOML.exists() else default_topology(env_name)
    topology["active_env"] = env_name
    topology["contract_env"] = relative_contract_env(env_name)
    topology.setdefault("providers", {provider: {"enabled": False} for provider in PROVIDERS})
    for provider in PROVIDERS:
        topology["providers"].setdefault(provider, {"enabled": False})
    topology.setdefault("instances", [])
    for instance in topology["instances"]:
        instance.setdefault("backend", service_backend(str(instance.get("service", ""))))
        if instance.get("service") == OBJECT_STORAGE_SERVICE:
            set_frontend_storage_defaults(instance, str(instance.get("env", env_name)))
    write_topology(topology)
    return topology


def read_topology() -> dict[str, Any]:
    data = tomllib.loads(RUNTIME_TOPOLOGY_TOML.read_text(encoding="utf-8"))
    data.setdefault("instances", [])
    data.setdefault("providers", {provider: {"enabled": False} for provider in PROVIDERS})
    for provider in PROVIDERS:
        data["providers"].setdefault(provider, {"enabled": False})
    return data


def write_topology(topology: dict[str, Any]) -> None:
    RUNTIME_TOPOLOGY_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f'active_env = "{topology.get("active_env", "devnet")}"',
        f'contract_env = "{topology.get("contract_env", relative_contract_env("devnet"))}"',
        "",
    ]
    providers = topology.get("providers", {})
    for provider in PROVIDERS:
        values = providers.get(provider, {"enabled": False}) if isinstance(providers, dict) else {"enabled": False}
        lines.append(f"[providers.{provider}]")
        for key, value in values.items():
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    for instance in topology.get("instances", []):
        lines.append("[[instances]]")
        for key, value in instance.items():
            lines.append(f"{key} = {toml_value(value)}")
        lines.append("")
    RUNTIME_TOPOLOGY_TOML.write_text("\n".join(lines), encoding="utf-8")


def find_instance(
    topology: dict[str, Any],
    env_name: str,
    name: str,
    service: str,
    provider: str,
) -> dict[str, Any] | None:
    for instance in topology.get("instances", []):
        if (
            instance.get("name") == name
            and instance.get("service") == service
            and instance.get("provider") == provider
            and instance.get("env", env_name) == env_name
        ):
            return instance
    return None


def new_instance(env_name: str, name: str, service: str, provider: str) -> dict[str, Any]:
    instance = {
        "name": name,
        "service": service,
        "provider": provider,
        "env": env_name,
        "backend": service_backend(service),
    }
    if service == OBJECT_STORAGE_SERVICE:
        set_frontend_storage_defaults(instance, env_name)
    return instance


def service_backend(service: str) -> str:
    return SERVICE_BACKENDS.get(service, "vm")


def prepare_running_frontend_artifacts(env_name: str) -> int:
    if not RUNTIME_TOPOLOGY_TOML.exists():
        return 0
    topology = read_topology()
    for instance in topology.get("instances", []):
        if (
            instance.get("service") == OBJECT_STORAGE_SERVICE
            and str(instance.get("env", env_name)) == env_name
            and instance.get("desired_state") == "running"
        ):
            missing_keys = missing_contract_keys(contract_env_path(env_name))
            if missing_keys:
                message = (
                    f"{contract_env_path(env_name)} is missing required contract keys: {', '.join(missing_keys)}. "
                    f"Run ./vidctl contract publish --env {env_name} --yes first."
                )
                print(message, file=sys.stderr)
                return 1
            provider = str(instance.get("provider", ""))
            missing_provider_keys = missing_object_storage_provider_keys(provider)
            if missing_provider_keys:
                print(object_storage_provider_error(provider, missing_provider_keys), file=sys.stderr)
                return 1
            return build_frontend_static(env_name)
    return 0


def missing_object_storage_provider_keys(provider: str) -> list[str]:
    env = command_env()
    required = {
        "cloudflare": (
            "CLOUDFLARE_API_TOKEN",
            "CLOUDFLARE_ACCOUNT_ID",
            "CLOUDFLARE_R2_ACCESS_KEY_ID",
            "CLOUDFLARE_R2_SECRET_ACCESS_KEY",
        ),
        "aws": ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"),
        "digitalocean": ("DIGITALOCEAN_TOKEN",),
        "alibaba": ("ALIBABA_CLOUD_ACCESS_KEY_ID", "ALIBABA_CLOUD_ACCESS_KEY_SECRET", "ALIBABA_CLOUD_REGION"),
        "gcp": (),
        "azure": (),
        "tencent": (),
    }.get(provider, ())
    return [key for key in required if not env.get(key)]


def object_storage_provider_error(provider: str, missing_keys: list[str]) -> str:
    secret_file = f"secrets/cloud/{provider}.env"
    if provider == "cloudflare":
        secret_file = "secrets/cloud/cloudflare.env"
    if provider == "digitalocean":
        secret_file = "secrets/cloud/digital-ocean.env"
    if provider == "alibaba":
        secret_file = "secrets/cloud/alibaba.env"
    return (
        f"{provider} frontend object storage is missing required credentials: "
        + ", ".join(missing_keys)
        + f". Add them to {secret_file} or export them before running ./vidctl infra."
    )


def missing_vm_provider_keys(provider: str) -> list[str]:
    env = command_env()
    required = {
        "aws": ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"),
        "gcp": ("GCP_PROJECT", "GCP_ZONE"),
        "azure": ("ARM_CLIENT_ID", "ARM_CLIENT_SECRET", "ARM_SUBSCRIPTION_ID", "ARM_TENANT_ID"),
        "alibaba": ("ALIBABA_CLOUD_ACCESS_KEY_ID", "ALIBABA_CLOUD_ACCESS_KEY_SECRET", "ALIBABA_CLOUD_REGION"),
        "digitalocean": ("DIGITALOCEAN_TOKEN",),
        "tencent": ("TENCENTCLOUD_SECRET_ID", "TENCENTCLOUD_SECRET_KEY", "TENCENTCLOUD_REGION"),
    }.get(provider, ())
    return [key for key in required if not env.get(key)]


def vm_provider_error(provider: str, missing_keys: list[str]) -> str:
    secret_file = f"secrets/cloud/{provider}.env"
    if provider == "digitalocean":
        secret_file = "secrets/cloud/digital-ocean.env"
    return (
        f"{provider} VM provisioning is missing required credentials: "
        + ", ".join(missing_keys)
        + f". Add them to {secret_file} or export them before running ./vidctl infra."
    )


def ensure_ssh_keypair(instance: dict[str, Any]) -> str:
    name = str(instance["name"])
    key_dir = SSH_KEY_ROOT / name
    private_key = key_dir / "id_ed25519"
    if not private_key.exists():
        key_dir.mkdir(parents=True, exist_ok=True)
        run(
            [
                "ssh-keygen",
                "-t",
                "ed25519",
                "-N",
                "",
                "-f",
                str(private_key),
                "-C",
                f"xaisen-{name}",
            ]
        )
        private_key.chmod(0o600)
        (key_dir / "id_ed25519.pub").chmod(0o644)
    return f"runtime/ssh_key/{name}"


def set_vm_defaults(instance: dict[str, Any]) -> None:
    service = str(instance.get("service", ""))
    provider = str(instance.get("provider", ""))
    instance.setdefault("port", SERVICE_PORTS.get(service, 0))
    instance.setdefault("size", VM_INSTANCE_SIZES.get(provider, ""))
    instance["ssh_key_dir"] = ensure_ssh_keypair(instance)


def build_frontend_static(env_name: str) -> int:
    contract_path = contract_env_path(env_name)
    values = read_env_file(contract_path)
    env = os.environ.copy()
    env.update(command_env())
    env["NEXT_PUBLIC_PACKAGE_ID"] = values.get("CONTRACT_PACKAGE_ID", "")
    env["NEXT_PUBLIC_REGISTRY_OBJECT_ID"] = values.get("CONTRACT_REGISTRY_OBJECT_ID", "")
    env["NEXT_PUBLIC_SUI_NETWORK"] = env_name
    service_dir = DOCKER_SERVICES[OBJECT_STORAGE_SERVICE]
    print(f"Building static frontend from {service_dir}")
    return run(["pnpm", "build"], cwd=service_dir, env=env)


def set_frontend_storage_defaults(instance: dict[str, Any], env_name: str) -> None:
    bucket = str(instance.get("bucket") or storage_bucket_name(env_name, str(instance.get("name", "frontend")), str(instance.get("provider", ""))))
    instance["backend"] = "object_storage"
    instance["bucket"] = bucket
    instance.setdefault("resource_id", bucket)
    instance.setdefault("artifact_dir", "services/frontend/out")
    if instance.get("provider") == "alibaba":
        instance.setdefault("region", command_env().get("ALIBABA_FRONTEND_REGION", "ap-southeast-1"))


def storage_bucket_name(env_name: str, name: str, provider: str) -> str:
    raw = f"xaisen-{env_name}-{provider}-{name}".lower()
    cleaned = "".join(char if char.isalnum() else "-" for char in raw)
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")[:63]


def missing_contract_keys(path: Path) -> list[str]:
    values = read_env_file(path)
    return [key for key in REQUIRED_CONTRACT_KEYS if not values.get(key)]


def validate_network(env_name: str) -> str:
    if env_name not in NETWORKS:
        raise ValueError(f"Unsupported environment {env_name!r}; expected one of {', '.join(NETWORKS)}.")
    return env_name


def desired_state_for(action: str) -> str:
    return {
        "start": "running",
        "pause": "stopped",
        "restart": "running",
        "kill": "deleted",
    }[action]


def relative_contract_env(env_name: str) -> str:
    return f"runtime/contract/{env_name}.env"


def default_topology(env_name: str) -> dict[str, Any]:
    return {
        "active_env": env_name,
        "contract_env": relative_contract_env(env_name),
        "providers": {provider: {"enabled": False} for provider in PROVIDERS},
        "instances": [],
    }


def record_history(
    command: str,
    env: str = "",
    name: str = "",
    service: str = "",
    provider: str = "",
    resource_id: str = "",
    previous_status: str = "",
    next_status: str = "",
    result: str | None = None,
    exit_code: int | None = None,
    result_for_code: int | None = None,
    error: str = "",
) -> None:
    if result_for_code is not None:
        exit_code = result_for_code
        result = "success" if result_for_code == 0 else "failure"
    if result is None:
        result = "success"
    if exit_code is None:
        exit_code = 0 if result == "success" else 1
    event = {
        "timestamp": timestamp(),
        "command": command,
        "env": env,
        "name": name,
        "service": service,
        "provider": provider,
        "resource_id": resource_id,
        "previous_status": previous_status,
        "next_status": next_status,
        "result": result,
        "exit_code": exit_code,
        "error": error,
    }
    RUNTIME_HISTORY_TOML.parent.mkdir(parents=True, exist_ok=True)
    with RUNTIME_HISTORY_TOML.open("a", encoding="utf-8") as history:
        history.write("[[events]]\n")
        for key, value in event.items():
            history.write(f"{key} = {toml_value(value)}\n")
        history.write("\n")


def timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(item) for item in value) + "]"
    if value is None:
        return '""'
    return json.dumps(str(value))
