"""Manage local (non-fleet) apps/bot dev-server sessions -- `vidctl utils
bot start/stop/list`. Lets an operator run one or more bot control-server
processes on their own machine, each creating+streaming into its own room
against the currently-deployed devnet contract, without hand-running
`pnpm dev` + `curl` every time. Each session is addressed by a small
integer id (starting at 1) so several can run side by side.

State lives in runtime/local_bots.toml (gitignored, same as every other
runtime/*.toml file) -- one [[bots]] row per known id, past or present.
"""

from __future__ import annotations

import os
import signal
import time
from dataclasses import dataclass

import tomllib
import urllib.error
import urllib.request

from . import bot_client, context, infra

BASE_PORT = 8095
# apps/bot also binds a second, independent port for its own Prometheus
# metrics server (BOT_METRICS_PORT, default 8096 -- see config.ts/index.ts)
# that isn't derived from PORT, so two local sessions on different PORTs
# still collide there unless it's allocated per-id too. Kept far from the
# BASE_PORT range so it never overlaps a control port even with many ids.
METRICS_BASE_PORT = 9095
BOT_APP_DIR = context.WORKER_DIR / "apps" / "bot"
HEALTHZ_TIMEOUT_SECONDS = 20.0
STOP_GRACE_SECONDS = 5.0


@dataclass
class LocalBotSession:
    id: int
    pid: int
    port: int
    bot_id: str
    room_id: str
    join_url: str
    started_at: str
    log_path: str


def _port_for(bot_local_id: int) -> int:
    return BASE_PORT + (bot_local_id - 1)


def _metrics_port_for(bot_local_id: int) -> int:
    return METRICS_BASE_PORT + (bot_local_id - 1)


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        # Process exists but is owned by someone else -- still "alive" for
        # our purposes (we just can't necessarily signal it later).
        return True
    return True


def read_sessions() -> dict[int, LocalBotSession]:
    if not context.RUNTIME_LOCAL_BOTS_TOML.exists():
        return {}
    try:
        data = tomllib.loads(context.RUNTIME_LOCAL_BOTS_TOML.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return {}
    result: dict[int, LocalBotSession] = {}
    for row in data.get("bots", []):
        if not isinstance(row, dict) or "id" not in row:
            continue
        try:
            bot_local_id = int(row["id"])
        except (TypeError, ValueError):
            continue
        result[bot_local_id] = LocalBotSession(
            id=bot_local_id,
            pid=int(row.get("pid", 0)),
            port=int(row.get("port", 0)),
            bot_id=str(row.get("bot_id", "")),
            room_id=str(row.get("room_id", "")),
            join_url=str(row.get("join_url", "")),
            started_at=str(row.get("started_at", "")),
            log_path=str(row.get("log_path", "")),
        )
    return result


def _write_sessions(sessions: dict[int, LocalBotSession]) -> None:
    context.RUNTIME_LOCAL_BOTS_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by vidctl utils bot", ""]
    for bot_local_id in sorted(sessions):
        session = sessions[bot_local_id]
        lines.append("[[bots]]")
        lines.append(f"id = {session.id}")
        lines.append(f"pid = {session.pid}")
        lines.append(f"port = {session.port}")
        lines.append(f"bot_id = {infra.toml_value(session.bot_id)}")
        lines.append(f"room_id = {infra.toml_value(session.room_id)}")
        lines.append(f"join_url = {infra.toml_value(session.join_url)}")
        lines.append(f"started_at = {infra.toml_value(session.started_at)}")
        lines.append(f"log_path = {infra.toml_value(session.log_path)}")
        lines.append("")
    context.RUNTIME_LOCAL_BOTS_TOML.write_text("\n".join(lines), encoding="utf-8")


def _wait_for_healthz(port: int, timeout: float) -> bool:
    deadline = time.monotonic() + timeout
    url = f"http://127.0.0.1:{port}/healthz"
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as response:
                if response.status == 200:
                    return True
        except (urllib.error.URLError, TimeoutError, OSError):
            pass
        time.sleep(0.5)
    return False


def start(bot_local_id: int) -> int:
    sessions = read_sessions()
    existing = sessions.get(bot_local_id)
    if existing is not None and _pid_alive(existing.pid):
        print(
            f"bot {bot_local_id}: already running (pid {existing.pid}, port {existing.port}) "
            "-- stop it first."
        )
        return 1

    env_path = BOT_APP_DIR / ".env"
    if not env_path.exists():
        print(
            f"bot {bot_local_id}: {env_path} does not exist -- "
            "`cp .env.example .env` in services/worker/apps/bot and fill it in first "
            "(PRIVATE_KEY, contract object IDs, CLIENT_URL)."
        )
        return 1

    port = _port_for(bot_local_id)
    session_env = dict(os.environ)
    session_env.update(context.read_env_file(env_path))
    session_env["PORT"] = str(port)
    session_env["BOT_METRICS_PORT"] = str(_metrics_port_for(bot_local_id))

    log_path = context.RUNTIME_LOCAL_BOTS_LOG_DIR / f"{bot_local_id}.log"
    # cwd=WORKER_DIR (pnpm workspace root), not apps/bot -- `pnpm --filter
    # bot dev` needs the full workspace to resolve @dvconf/shared etc.,
    # same convention DOCKER_SERVICES/apps' build context already uses
    # (see context.py's WORKER_DIR comment).
    pid = context.run_detached(
        ["pnpm", "--filter", "bot", "dev"], cwd=context.WORKER_DIR, env=session_env, log_path=log_path
    )

    print(f"bot {bot_local_id}: started pid {pid} on port {port}, waiting for healthz...")
    if not _wait_for_healthz(port, HEALTHZ_TIMEOUT_SECONDS):
        print(
            f"bot {bot_local_id}: did not become healthy within {HEALTHZ_TIMEOUT_SECONDS:.0f}s "
            f"-- check {log_path}"
        )
        # Record the pid even on failure -- otherwise a hung (not crashed)
        # process leaks untracked, with no `vidctl utils bot stop <id>` able
        # to find and kill it (see the room-creation-failure branch below,
        # same reasoning).
        sessions[bot_local_id] = LocalBotSession(
            id=bot_local_id,
            pid=pid,
            port=port,
            bot_id="",
            room_id="",
            join_url="",
            started_at=infra.timestamp(),
            log_path=str(log_path),
        )
        _write_sessions(sessions)
        return 1

    result = bot_client.create_room_local(port, media_mode="both")
    if result is None:
        print(
            f"bot {bot_local_id}: process is up (pid {pid}, port {port}) but room creation "
            f"failed -- check {log_path}. Run `vidctl utils bot stop {bot_local_id}` to clean up."
        )
        sessions[bot_local_id] = LocalBotSession(
            id=bot_local_id,
            pid=pid,
            port=port,
            bot_id="",
            room_id="",
            join_url="",
            started_at=infra.timestamp(),
            log_path=str(log_path),
        )
        _write_sessions(sessions)
        return 1

    session = LocalBotSession(
        id=bot_local_id,
        pid=pid,
        port=port,
        bot_id=str(result.get("botId", "")),
        room_id=str(result.get("roomId", "")),
        join_url=str(result.get("joinUrl", "")),
        started_at=infra.timestamp(),
        log_path=str(log_path),
    )
    sessions[bot_local_id] = session
    _write_sessions(sessions)

    print(f"bot {bot_local_id}: room {session.room_id}")
    print(f"bot {bot_local_id}: join at {session.join_url}")
    return 0


def stop(bot_local_id: int) -> int:
    sessions = read_sessions()
    session = sessions.get(bot_local_id)
    if session is None:
        print(f"bot {bot_local_id}: no known session.")
        return 1

    if session.bot_id:
        result = bot_client.delete_room_local(session.port, session.bot_id)
        if result is None:
            print(f"bot {bot_local_id}: DELETE /bots/{session.bot_id} failed (continuing anyway).")

    if _pid_alive(session.pid):
        try:
            os.kill(session.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        deadline = time.monotonic() + STOP_GRACE_SECONDS
        while time.monotonic() < deadline and _pid_alive(session.pid):
            time.sleep(0.2)
        if _pid_alive(session.pid):
            try:
                os.kill(session.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass

    del sessions[bot_local_id]
    _write_sessions(sessions)
    print(f"bot {bot_local_id}: stopped.")
    return 0


def list_bots() -> int:
    sessions = read_sessions()
    if not sessions:
        print("No local bot sessions.")
        return 0

    print(f"{'ID':<4}{'STATUS':<10}{'PORT':<7}{'ROOM ID':<22}{'JOIN URL'}")
    for bot_local_id in sorted(sessions):
        session = sessions[bot_local_id]
        status = "running" if _pid_alive(session.pid) else "dead"
        room_display = (session.room_id[:18] + "..") if len(session.room_id) > 20 else session.room_id
        print(
            f"{session.id:<4}{status:<10}{session.port:<7}{room_display:<22}{session.join_url}"
        )
    return 0
