from __future__ import annotations

import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

from .context import (
    ANSIBLE_DIR,
    DOCKER_SERVICES,
    REGISTRY_SECRETS_DIR,
    RUNTIME_REGISTRY_TOML,
    command_env,
    contract_env_path,
    git_short_sha,
    read_env_file,
    run,
)

DEPLOYED_TAGS_YAML = ANSIBLE_DIR / "vars" / "deployed_tags.generated.yml"

DEFAULT_PROVIDER = "alibaba"

# The Xaisen fleet (ECS/EC2/Droplet/etc.) is x86_64; build for that explicitly
# so images built on arm64 dev machines (e.g. Apple Silicon) still run on the
# deployed hosts instead of crash-looping with "exec format error".
TARGET_PLATFORM = "linux/amd64"


@dataclass(frozen=True)
class RegistryConfig:
    provider: str
    prefix: str
    username: str | None = None
    password: str | None = None


@dataclass(frozen=True)
class RegistryState:
    provider: str
    host: str
    prefix: str
    images: dict[str, str]
    deployed: dict[str, str]


def validate_provider(provider: str) -> str:
    value = provider.strip()
    if not value or value != Path(value).name:
        raise ValueError("Registry provider must be a secrets/registry env-file basename.")
    return value


def registry_env_path(provider: str) -> Path:
    return REGISTRY_SECRETS_DIR / f"{validate_provider(provider)}.env"


def provider_config(provider: str = DEFAULT_PROVIDER, *, require_credentials: bool = False) -> RegistryConfig:
    provider = validate_provider(provider)
    path = registry_env_path(provider)
    if path.exists():
        values = read_env_file(path)
        prefix = values.get("REGISTRY_PREFIX", "").strip().rstrip("/")
        username = values.get("REGISTRY_USERNAME", "").strip() or None
        password = values.get("REGISTRY_PASSWORD", "").strip() or None
        if not prefix:
            raise ValueError(f"REGISTRY_PREFIX is missing in {path}.")
        if require_credentials and (not username or not password):
            raise ValueError(f"REGISTRY_USERNAME and REGISTRY_PASSWORD are required in {path}.")
        return RegistryConfig(provider=provider, prefix=prefix, username=username, password=password)

    if provider == DEFAULT_PROVIDER:
        env = command_env()
        prefix = env.get("ALICLOUD_CR_REGISTRY", "").strip().rstrip("/")
        username = env.get("ALICLOUD_CR_USERNAME", "").strip() or None
        password = env.get("ALICLOUD_CR_PASSWORD", "").strip() or None
        if prefix:
            if require_credentials and (not username or not password):
                raise ValueError("ALICLOUD_CR_USERNAME and ALICLOUD_CR_PASSWORD are required.")
            return RegistryConfig(provider=provider, prefix=prefix, username=username, password=password)

    raise ValueError(f"Registry provider config not found: {path}")


def registry_host(prefix: str) -> str:
    return prefix.split("/", 1)[0]


def selected_services(service: str | None, all_services: bool) -> list[str]:
    if all_services:
        return list(DOCKER_SERVICES)
    if service:
        return [service]
    raise ValueError("Select a service with --service or all services with --all.")


def runtime_images(prefix: str) -> dict[str, str]:
    return {service: f"{prefix}/{service}" for service in sorted(DOCKER_SERVICES)}


def existing_deployed_tags() -> dict[str, str]:
    if not RUNTIME_REGISTRY_TOML.exists():
        return {}
    try:
        data = tomllib.loads(RUNTIME_REGISTRY_TOML.read_text())
    except tomllib.TOMLDecodeError:
        return {}
    deployed = data.get("deployed")
    return {str(k): str(v) for k, v in deployed.items()} if isinstance(deployed, dict) else {}


def write_runtime_registry(config: RegistryConfig) -> None:
    RUNTIME_REGISTRY_TOML.parent.mkdir(parents=True, exist_ok=True)
    deployed = existing_deployed_tags()
    lines = [
        "# generated by vidctl",
        "# selected registry provider and image repositories",
        f'provider = "{config.provider}"',
        f'registry_host = "{registry_host(config.prefix)}"',
        f'registry_prefix = "{config.prefix}"',
        "",
        "[images]",
    ]
    for service, image in runtime_images(config.prefix).items():
        lines.append(f'{service} = "{image}"')
    lines += ["", "[deployed]"]
    for service, tag in sorted(deployed.items()):
        lines.append(f'{service} = "{tag}"')
    RUNTIME_REGISTRY_TOML.write_text("\n".join(lines) + "\n")


def write_deployed_tag(service: str, tag: str) -> None:
    deployed = existing_deployed_tags()
    deployed[service] = tag

    if RUNTIME_REGISTRY_TOML.exists():
        text = RUNTIME_REGISTRY_TOML.read_text()
        if "[deployed]" in text:
            head = text.split("[deployed]", 1)[0].rstrip("\n")
        else:
            head = text.rstrip("\n")
        lines = [head, "", "[deployed]"]
        for name, deployed_tag in sorted(deployed.items()):
            lines.append(f'{name} = "{deployed_tag}"')
        RUNTIME_REGISTRY_TOML.write_text("\n".join(lines) + "\n")

    DEPLOYED_TAGS_YAML.parent.mkdir(parents=True, exist_ok=True)
    yaml_lines = ["# generated by vidctl - service -> currently published image tag"] + [
        f"{name}: {deployed_tag}" for name, deployed_tag in sorted(deployed.items())
    ]
    DEPLOYED_TAGS_YAML.write_text("\n".join(yaml_lines) + "\n")


def read_runtime_registry() -> RegistryState:
    if not RUNTIME_REGISTRY_TOML.exists():
        raise ValueError(
            f"{RUNTIME_REGISTRY_TOML} is missing. Run ./vidctl registry login --provider <provider> first."
        )
    try:
        data = tomllib.loads(RUNTIME_REGISTRY_TOML.read_text())
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"{RUNTIME_REGISTRY_TOML} is invalid: {exc}") from exc

    provider = str(data.get("provider", "")).strip()
    host = str(data.get("registry_host", "")).strip()
    prefix = str(data.get("registry_prefix", "")).strip().rstrip("/")
    images = data.get("images")
    if not provider or not host or not prefix or not isinstance(images, dict):
        raise ValueError(
            f"{RUNTIME_REGISTRY_TOML} is incomplete. Run ./vidctl registry login --provider <provider> first."
        )

    resolved_images = {str(name): str(image).strip().rstrip("/") for name, image in images.items() if str(image).strip()}
    missing = sorted(set(DOCKER_SERVICES) - set(resolved_images))
    if missing:
        raise ValueError(f"{RUNTIME_REGISTRY_TOML} is missing image entries: {', '.join(missing)}.")
    deployed = data.get("deployed")
    resolved_deployed = {str(k): str(v) for k, v in deployed.items()} if isinstance(deployed, dict) else {}
    return RegistryState(provider=provider, host=host, prefix=prefix, images=resolved_images, deployed=resolved_deployed)


def image_name(service: str, tag: str) -> str:
    state = read_runtime_registry()
    image = state.images.get(service)
    if not image:
        raise ValueError(f"{RUNTIME_REGISTRY_TOML} has no image entry for service: {service}.")
    return f"{image}:{tag}"


def login(provider: str = DEFAULT_PROVIDER) -> int:
    try:
        config = provider_config(provider, require_credentials=True)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    code = docker_login(config)
    if code == 0:
        write_runtime_registry(config)
    return code


def docker_login(config: RegistryConfig) -> int:
    return run(
        ["docker", "login", registry_host(config.prefix), "--username", config.username, "--password-stdin"],
        input_text=f"{config.password}\n",
    )


def build(service: str | None, all_services: bool, tag: str | None) -> int:
    return each_service("build", service, all_services, tag)


def push(service: str | None, all_services: bool, tag: str | None) -> int:
    return each_service("push", service, all_services, tag)


def publish(service: str | None, all_services: bool, tag: str | None) -> int:
    code = build(service, all_services, tag)
    if code != 0:
        return code
    return push(service, all_services, tag)


def each_service(action: str, service: str | None, all_services: bool, tag: str | None) -> int:
    try:
        services = selected_services(service, all_services)
        resolved_tag = tag or git_short_sha()
        for name in services:
            context = DOCKER_SERVICES[name]
            image = image_name(name, resolved_tag)
            build_args = frontend_contract_build_args() if name == "frontend" else {}
            code = run_docker_action(action, image, context, build_args)
            if code != 0:
                return code
            if action == "push":
                write_deployed_tag(name, resolved_tag)
        return 0
    except KeyError as exc:
        print(f"Unknown service: {exc.args[0]}", file=sys.stderr)
        return 2
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2


def frontend_contract_build_args() -> dict[str, str]:
    from . import infra

    env_name = infra.active_stack()
    values = read_env_file(contract_env_path(env_name))
    return {
        "NEXT_PUBLIC_PACKAGE_ID": values.get("CONTRACT_PACKAGE_ID", ""),
        "NEXT_PUBLIC_REGISTRY_OBJECT_ID": values.get("CONTRACT_REGISTRY_OBJECT_ID", ""),
        "NEXT_PUBLIC_SUI_NETWORK": env_name,
    }


def run_docker_action(action: str, image: str, context: Path, build_args: dict[str, str] | None = None) -> int:
    if action == "build":
        args = ["docker", "buildx", "build", "--platform", TARGET_PLATFORM, "--load", "-t", image]
        for key, value in (build_args or {}).items():
            args.extend(["--build-arg", f"{key}={value}"])
        args.append(str(context))
        return run(args)
    if action == "push":
        return run(["docker", "push", image])
    print(f"Unknown registry action: {action}", file=sys.stderr)
    return 2
