"""`vidctl utils worker status <hostname>` -- SSH into a deployed worker VM
and show the Docker state of one worker's container: ps/inspect summary,
a resource snapshot, and recent logs.

Takes the same public hostname a browser/relay client would use (e.g.
`akamai-003-signaling-1.96-126-106-95.sslip.io`, built by
worker_env.yml/Caddyfile.j2 as `<worker_key>.<ip-with-dashes>.sslip.io`) so
an operator can paste a URL straight out of Grafana/logs without having to
separately know the host id or SSH details. `<worker_key>` is
`<provider>-<host>-<service>-<index>` (see topology.py's worker_identifier(),
the one-directional builder this module's parse_worker_hostname() reverses),
and the container it maps to is always named `xaisen-<worker_key>` (see
run_container.yml).
"""

from __future__ import annotations

import re
import subprocess
import sys
import uuid
from dataclasses import dataclass
from datetime import datetime

import tomllib

from . import context, infra

SSH_TIMEOUT_SECONDS = 25
SSH_CONNECT_TIMEOUT_SECONDS = 8
LOG_TAIL_LINES = 40

_HOST_ID_RE = re.compile(r"^\d{3,}$")

# Liveness-experiment support (`vidctl utils worker start/stop` as the
# ground-truth stop/start timestamps for the Grafana "Liveness" table -- see
# docs' plan). Pushed to the observer Pushgateway; correlated later against
# the relay's dvconf_relay_down_hint_* and validator-daemon's
# dvconf_worker_down_vote_total by cli/observer/worker_liveness.py.
_LIVENESS_JOB_NAME = "worker_liveness"
_LIVENESS_ACTION_METRIC = "xaisen_worker_action_timestamp_seconds"
_LIVENESS_HELP_TEXT = (
    "Unix timestamp of a vidctl utils worker start/stop action, pushed by "
    "worker_status.py for the Liveness experiment table."
)


@dataclass
class LivenessEvent:
    event_id: str
    worker: str
    stopped_at: str
    started_at: str = ""
    resolved: bool = False


def _read_liveness_events() -> list[LivenessEvent]:
    if not context.RUNTIME_WORKER_LIVENESS_TOML.exists():
        return []
    try:
        data = tomllib.loads(context.RUNTIME_WORKER_LIVENESS_TOML.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError:
        return []
    events: list[LivenessEvent] = []
    for row in data.get("events", []):
        if not isinstance(row, dict) or "event_id" not in row:
            continue
        events.append(
            LivenessEvent(
                event_id=str(row.get("event_id", "")),
                worker=str(row.get("worker", "")),
                stopped_at=str(row.get("stopped_at", "")),
                started_at=str(row.get("started_at", "")),
                resolved=bool(row.get("resolved", False)),
            )
        )
    return events


def _write_liveness_events(events: list[LivenessEvent]) -> None:
    context.RUNTIME_WORKER_LIVENESS_TOML.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by vidctl utils worker start/stop", ""]
    for event in events:
        lines.append("[[events]]")
        lines.append(f"event_id = {infra.toml_value(event.event_id)}")
        lines.append(f"worker = {infra.toml_value(event.worker)}")
        lines.append(f"stopped_at = {infra.toml_value(event.stopped_at)}")
        lines.append(f"started_at = {infra.toml_value(event.started_at)}")
        lines.append(f"resolved = {infra.toml_value(event.resolved)}")
        lines.append("")
    context.RUNTIME_WORKER_LIVENESS_TOML.write_text("\n".join(lines), encoding="utf-8")


def _open_liveness_event(events: list[LivenessEvent], worker_key: str) -> LivenessEvent | None:
    # Most-recent-first: a worker can be stopped/started more than once
    # across separate experiments, and only the latest unresolved stop is
    # the one a subsequent start resolves.
    for event in reversed(events):
        if event.worker == worker_key and not event.resolved:
            return event
    return None


def _push_liveness_action(worker_key: str, event_id: str, action: str, at_iso: str) -> None:
    # Deferred import: avoids a hard dependency on cli.observer (and its
    # transitive imports) for every `vidctl utils worker` invocation that
    # never touches liveness tracking.
    from .observer import pushgateway

    try:
        at_seconds = datetime.fromisoformat(at_iso).timestamp()
    except ValueError:
        return
    samples = [(_LIVENESS_ACTION_METRIC, {"worker": worker_key, "event_id": event_id, "action": action}, at_seconds)]
    code = pushgateway.push_samples(_LIVENESS_JOB_NAME, worker_key, samples, _LIVENESS_HELP_TEXT)
    if code != 0:
        print(f"{worker_key}: liveness-metric push failed (non-fatal, see warning above).", file=sys.stderr)


@dataclass
class WorkerRef:
    provider: str
    host: str
    service: str
    index: int
    worker_key: str

    @property
    def container_name(self) -> str:
        return f"xaisen-{self.worker_key}"


def parse_worker_hostname(hostname: str) -> WorkerRef | None:
    """Reverse worker_identifier(): pull `<provider>-<host>-<service>-<index>`
    back out of a full sslip.io hostname (or a bare worker key, for
    convenience). Service names may themselves contain dashes (cp-daemon,
    validator-daemon), so `index` and `provider`/`host` are peeled off the
    two ends first and everything left in the middle is the service name.
    Returns None on anything that doesn't parse -- callers print their own
    usage-appropriate error rather than this raising.
    """
    worker_key = hostname.split(".", 1)[0]
    parts = worker_key.split("-")
    if len(parts) < 4:
        return None

    provider, host = parts[0], parts[1]
    index_str = parts[-1]
    service = "-".join(parts[2:-1])

    if provider not in infra.PROVIDERS:
        return None
    if not _HOST_ID_RE.match(host):
        return None
    if not index_str.isdigit():
        return None
    if service not in infra.DOCKER_SERVICES:
        return None

    return WorkerRef(
        provider=provider,
        host=host,
        service=service,
        index=int(index_str),
        worker_key=worker_key,
    )


def _run_ssh(host: str, address: str, user: str, remote_command: str) -> subprocess.CompletedProcess[str] | None:
    key_path = infra.SSH_KEY_ROOT / host / "id_ed25519"
    if not key_path.exists():
        return None
    try:
        return subprocess.run(
            [
                "ssh",
                "-o", "StrictHostKeyChecking=no",
                "-o", f"ConnectTimeout={SSH_CONNECT_TIMEOUT_SECONDS}",
                "-i", str(key_path),
                f"{user}@{address}",
                remote_command,
            ],
            capture_output=True,
            text=True,
            timeout=SSH_TIMEOUT_SECONDS,
            check=False,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None


def _docker_status_command(container_name: str) -> str:
    # Chained with `;` (not `&&`) so a not-found container still shows the
    # `docker ps` line (which reports its absence) instead of aborting the
    # whole probe on the first failing subcommand.
    ps_format = "table {{.Names}}\\t{{.Status}}\\t{{.Image}}\\t{{.Ports}}"
    inspect_format = (
        "Status: {{.State.Status}}"
        "  Health: {{if .State.Health}}{{.State.Health.Status}}{{else}}n/a{{end}}"
        "  Restarts: {{.RestartCount}}"
        "  StartedAt: {{.State.StartedAt}}"
    )
    return (
        f"echo '=== docker ps ==='; "
        f"docker ps -a --filter name=^/{container_name}$ --format '{ps_format}'; "
        f"echo; echo '=== container state ==='; "
        f"docker inspect {container_name} --format '{inspect_format}' 2>&1; "
        f"echo; echo '=== resource snapshot ==='; "
        f"docker stats --no-stream {container_name} 2>&1; "
        f"echo; echo '=== last {LOG_TAIL_LINES} log lines ==='; "
        f"docker logs --tail {LOG_TAIL_LINES} {container_name} 2>&1"
    )


def status(hostname: str) -> int:
    ref = parse_worker_hostname(hostname)
    if ref is None:
        print(
            f"Could not parse '{hostname}' as a worker hostname. Expected "
            "<provider>-<host>-<service>-<index>[.<ip-with-dashes>.sslip.io], "
            "e.g. akamai-003-signaling-1.96-126-106-95.sslip.io.",
            file=sys.stderr,
        )
        return 2

    address = infra.host_address(ref.host)
    if not address:
        message = (
            f"No address on record for host {ref.host} -- run `vidctl infra inventory` "
            "first, or check the host is actually provisioned."
        )
        print(message, file=sys.stderr)
        infra.record_history(
            "utils worker status",
            service=ref.service,
            provider=ref.provider,
            resource_id=ref.container_name,
            result_for_code=1,
            error=message,
        )
        return 1

    user = infra.host_ssh_user(ref.host)
    result = _run_ssh(ref.host, address, user, _docker_status_command(ref.container_name))
    if result is None:
        message = f"Could not SSH to {ref.host} ({address}) -- missing key or connection failed."
        print(message, file=sys.stderr)
        infra.record_history(
            "utils worker status",
            service=ref.service,
            provider=ref.provider,
            resource_id=ref.container_name,
            result_for_code=1,
            error=message,
        )
        return 1

    print(f"{ref.container_name} @ {ref.provider} host {ref.host} ({address})")
    print()
    print(result.stdout.rstrip())
    if result.stderr.strip():
        print()
        print(result.stderr.rstrip(), file=sys.stderr)

    infra.record_history(
        "utils worker status",
        service=ref.service,
        provider=ref.provider,
        resource_id=ref.container_name,
        result_for_code=0 if result.returncode == 0 else 1,
    )
    return 0 if result.returncode == 0 else 1


def start(hostname: str) -> int:
    """`docker start` a single worker's container. Thin wrapper over
    infra.toggle_container's ansible fast-path (skips site.yml's
    common/docker_service roles -- only valid when the container already
    exists with correct config from an earlier `vidctl scenario apply`)."""
    return _toggle(hostname, "start")


def stop(hostname: str) -> int:
    """`docker stop` a single worker's container. See start()'s docstring."""
    return _toggle(hostname, "stop")


def _toggle(hostname: str, action: str) -> int:
    ref = parse_worker_hostname(hostname)
    if ref is None:
        print(
            f"Could not parse '{hostname}' as a worker hostname. Expected "
            "<provider>-<host>-<service>-<index>[.<ip-with-dashes>.sslip.io], "
            "e.g. akamai-003-signaling-1.96-126-106-95.sslip.io.",
            file=sys.stderr,
        )
        return 2

    print(f"{ref.container_name} @ {ref.provider} host {ref.host}: docker {action}...")
    # toggle_container() already calls infra.record_history() itself -- no
    # separate call needed here (unlike status(), which does its own raw SSH
    # and has no such built-in bookkeeping).
    code = infra.toggle_container(host_limit=ref.host, container_name=ref.container_name, action=action)
    if code == 0:
        print(f"{ref.container_name}: {action} succeeded.")
        _record_liveness_event(ref.worker_key, action)
    else:
        print(f"{ref.container_name}: {action} failed (exit {code}) -- see ansible output above.", file=sys.stderr)
    return code


def _record_liveness_event(worker_key: str, action: str) -> None:
    """Ground-truth stop/start timestamps for the Liveness experiment table
    -- called only after `_toggle()` confirms the docker action succeeded.
    A `stop` opens a new event; a `start` resolves the most recent open
    event for this worker (if any -- a `start` with no matching open `stop`
    is a no-op here, since there is nothing to correlate it against)."""
    events = _read_liveness_events()
    if action == "stop":
        event = LivenessEvent(event_id=uuid.uuid4().hex, worker=worker_key, stopped_at=infra.timestamp())
        events.append(event)
        _write_liveness_events(events)
        _push_liveness_action(worker_key, event.event_id, "stop", event.stopped_at)
        return

    event = _open_liveness_event(events, worker_key)
    if event is None:
        return
    event.started_at = infra.timestamp()
    event.resolved = True
    _write_liveness_events(events)
    _push_liveness_action(worker_key, event.event_id, "start", event.started_at)
