---
# Role-level variables for routes (API/frontend) nodes.
role_name: routes
client_container_name: xaisen-client
routes_container_name: xaisen-routes
proxy_container_name: xaisen-proxy
proxy_config_path: /etc/xaisen/Caddyfile
client_oss: false
