from __future__ import annotations

import subprocess
import sys

from ..context import PULUMI_DIR
from .history import record_history
from .topology import active_stack


def inventory() -> int:
    # Deferred self-import: GENERATED_INVENTORY/command_env are patched by
    # tests as flat cli.infra attributes -- looking them up through the
    # package at call time is what makes those patches take effect here.
    from .. import infra

    stack = active_stack()
    try:
        raw = subprocess.check_output(
            ["pulumi", "stack", "output", "ansibleInventory", "--json", "--stack", stack],
            cwd=PULUMI_DIR,
            env=infra.command_env(),
            text=True,
        )
    except subprocess.CalledProcessError as exc:
        message = f"Unable to read Pulumi ansibleInventory output: {exc}"
        print(message, file=sys.stderr)
        record_history("infra inventory", env=stack, result_for_code=1, error=message)
        return 1

    try:
        import yaml
    except ImportError:
        message = "PyYAML is missing. Run: ./vidctl bootstrap"
        print(message, file=sys.stderr)
        record_history("infra inventory", env=stack, result_for_code=1, error=message)
        return 1

    import json

    infra.GENERATED_INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    infra.GENERATED_INVENTORY.write_text(
        "# Generated by ./vidctl infra inventory\n" + yaml.safe_dump(json.loads(raw), sort_keys=False),
        encoding="utf-8",
    )
    record_history("infra inventory", env=stack, result="success", exit_code=0)
    return 0


def host_address(host: str) -> str:
    from .. import infra

    try:
        import yaml
    except ImportError:
        return ""
    if not infra.GENERATED_INVENTORY.exists():
        return ""
    try:
        data = yaml.safe_load(infra.GENERATED_INVENTORY.read_text(encoding="utf-8"))
        host_entry = data["all"]["children"]["xaisen"]["hosts"].get(host, {})
        return str(host_entry.get("ansible_host", ""))
    except (KeyError, TypeError, AttributeError):
        return ""


def host_ssh_user(host: str) -> str:
    """SSH login user Pulumi's create_vm() configured for this host (root,
    azureuser, ubuntu, ...) -- see inventory.py's `ansible_user` propagation
    from each compute/<provider>.py's create_vm() return value. Defaults to
    "root" (every non-Azure/AWS/GCP provider today) if the inventory hasn't
    been generated yet or the entry is missing ansible_user.
    """
    from .. import infra

    try:
        import yaml
    except ImportError:
        return "root"
    if not infra.GENERATED_INVENTORY.exists():
        return "root"
    try:
        data = yaml.safe_load(infra.GENERATED_INVENTORY.read_text(encoding="utf-8"))
        host_entry = data["all"]["children"]["xaisen"]["hosts"].get(host, {})
        return str(host_entry.get("ansible_user") or "root")
    except (KeyError, TypeError, AttributeError):
        return "root"


def registry_status(host: str, worker_key: str, address: str) -> str:
    from .. import infra

    key_path = infra.SSH_KEY_ROOT / host / "id_ed25519"
    if not address or not key_path.exists():
        return "unknown (host unreachable)"
    container_name = f"xaisen-{worker_key}"
    try:
        result = subprocess.run(
            [
                "ssh",
                "-o", "StrictHostKeyChecking=no",
                "-o", "ConnectTimeout=8",
                "-i", str(key_path),
                f"root@{address}",
                f"docker logs {container_name} 2>&1 | grep -E 'operator address|node_id=|bootstrap failed' | tail -40",
            ],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (subprocess.TimeoutExpired, OSError) as exc:
        return f"unknown ({exc})"

    output = result.stdout.strip()
    if not output:
        return "unknown (no operator log lines found)"

    # docker logs preserves history across `docker restart` (same container),
    # so only consider lines from the most recent boot's operator address block.
    lines = output.splitlines()
    last_boot_start = max(
        (i for i, line in enumerate(lines) if "operator address" in line),
        default=0,
    )
    lines = lines[last_boot_start:]

    if any("bootstrap failed" in line for line in lines):
        error_line = next((line for line in lines if "bootstrap failed" in line), "")
        return f"not registered ({error_line.split('Error:', 1)[-1].strip() or 'see logs'})"
    node_id_line = next(
        (line for line in reversed(lines) if "node_id=" in line),
        "",
    )
    if node_id_line:
        node_id = node_id_line.split("node_id=", 1)[-1].split(";")[0].strip()
        return f"registered (node_id={node_id})"
    return "unknown (unrecognized log output)"
