name = "digitalocean-devnet-sample"
env = "devnet"

[contract]
gas_budget = ""
create_registry_if_missing = false
force = false

[registry]
provider = "digitalocean"
tag = ""

[[frontends]]
name = "site-2-bucket"
object = "frontend"
provider = "alibaba"

[[instances]]
name = "node-1"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"

[[instances]]
name = "node-1"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"

[[instances]]
name = "node-1"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"

[[instances]]
name = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
instance_index = 1

[[instances]]
name = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
instance_index = 2

[[instances]]
name = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
instance_index = 3

[[instances]]
name = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
instance_index = 4

[[instances]]
name = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
instance_index = 5
