name = "digitalocean-devnet-sample"
env = "devnet"

[contract]
gas_budget = ""
create_registry_if_missing = false
force = false

[registry]
provider = "digitalocean"
tag = ""

[[frontends]]
name = "site-2-bucket"
object = "frontend"
provider = "alibaba"

[[workers]]
host = "node-1"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-1"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-1"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-1"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-1"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-1"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-1"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-2"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-2"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-2"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-2"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-2"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-2"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-2"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-2"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-3"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-3"
service = "signaling"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-3"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-3"
service = "relay"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-3"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-3"
service = "cp-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2

[[workers]]
host = "node-3"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 1

[[workers]]
host = "node-3"
service = "validator-daemon"
provider = "digitalocean"
size = "s-4vcpu-8gb"
worker_index = 2
