name = "baseline-devnet"
env = "devnet"

[contract]
gas_budget = ""
create_registry_if_missing = false
force = false

[registry]
tag = ""

[[workers]]
host = "node-1"
service = "signaling"
provider = "digitalocean"
size = "s-1vcpu-1gb"
worker_index = 1

[[workers]]
host = "node-1"
service = "relay"
provider = "digitalocean"
size = "s-1vcpu-1gb"
worker_index = 1

[[workers]]
host = "node-2"
service = "cp-daemon"
provider = "digitalocean"
size = "s-1vcpu-1gb"
worker_index = 1

[[workers]]
host = "node-3"
service = "validator-daemon"
provider = "digitalocean"
size = "s-1vcpu-1gb"
worker_index = 1
