[package]
name = "dvconf_role_voting"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
dvconf_contracts = { local = "../contract" }

[addresses]
dvconf_role_voting = "0x0"

[environments]
local = "8f16e176"
devnet = "11888def"
testnet = "4c78adac"
