SHELL := /bin/sh

TF_ENV ?=

.PHONY: help list-envs

help:
	@printf '%s\n' "Targets:"
	@printf '%s\n' "  make list-envs   List supported Terraform provider roots"
	@printf '%s\n' "  make help        Show this help"

list-envs:
	@printf '%s\n' "Supported Terraform provider roots:"
	@printf '%s\n' "  aws"
	@printf '%s\n' "  digital-ocean"
	@printf '%s\n' "  hetzner"
	@printf '%s\n' "  alibaba-cloud"
